apiVersion: v1
kind: Service
metadata:
  name: customers
  labels:
    app: customers
spec:
  type: ClusterIP
  selector:
    app: customers
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080